controllers/BlocosController.php
<?
namespace app\controllers;

use app\models\BlocosModel;
use yii\web\Controller;         
use yii\data\Pagination;


class BlocosController extends Controller {

    public static function listaBlocosSelect() 
    {
        $query = BlocosModel::find();

        return $query->orderBy('id')->all();
    }

    public static function listaBlocosEdit($from) 
    {
        $query = BlocosModel::find();
        $data = $query->where(['from_condominio' => $from])->orderBy('nomeBloco')->all();
        return $data;
    }

    public function actionListaBlocosApi()
    {
        $request = \yii::$app->request;
        $query = BlocosModel::find();
        $data = $query->where(['from_condominio' => $request->post()])->orderBy('nomeBloco')->all();

        $dados = array();
        $i = 0;

        foreach($data as $d) {
            $dados[$i]['id'] = $d['id'];
            $dados[$i]['nomeBloco'] = $d['nomeBloco'];
            $i++;
        }
        return json_encode($dados);
    }

    public function actionCadastroBlocos() {
        return $this->render('cadastro-blocos');
    }

    public function actionRealizaCadastroBlocos()
    {
        $request = \yii::$app->request;

        if ($request->isPost) {
            $model = new BlocosModel();
            $model->attributes = $request->post();
            $model->save();
            return $this->redirect(['blocos/cadastro-blocos']);
        }

        return $this->render('cadastro-blocos');
    }

    public function actionEditaBlocos() 
    {
        $request = \yii::$app->request;
        $this->layout = false;
        if ($request->isGet) {
            $query = BlocosModel::find();
            $blocos = $query->where(['id' => $request->get()])->one();
        }

        return $this->render('edita-blocos', [
            'edit' => $blocos
        ]);
    }

    public function actionRealizaEdicaoBlocos() {
        $request = \yii::$app->request;

        if($request->isPost){

            $model = BlocosModel::findOne($request->post('id'));
            $model->attributes = $request->post();

            if($model->update()){
                return $this->redirect(['blocos/listar-blocos']);
            } else {
                return $this->redirect(['blocos/listar-blocos']);
            }
        }  
    }

    public function actionListarBlocos() {

        $query = (new \yii\db\Query())
        ->select(
        'condo.id as idCondo,
        bloco.id,
        condo.nome,
        bloco.nomeBloco,
        bloco.Andares,
        bloco.qtUnidadesAndar,
        bloco.dataCadastro'
        )
        ->from('jp_bloco bloco')
        ->innerJoin('jp_condominio condo', 'condo.id = bloco.from_condominio');

        $paginacao = new Pagination([
            'defaultPageSize' => 5,
            'totalCount' => $query->count(),
        ]);

        $blocos = $query->orderBy('nomeBloco')
            ->offset($paginacao->offset)
            ->limit($paginacao->limit)
            ->all();
        
        return $this->render('listar-blocos',[
            'blocos' => $blocos,
            'paginacao' => $paginacao,
        ]);

    }
    
}

?>

views/blocos/cadastro-blocos.php
<?
use app\controllers\CondominiosController;
use yii\helpers\Url;
?>

<div class="row justify-content-center">

    <h1 class="text-center text-dark">Cadastro de Bloco</h1>
    <form id="form-bloco" class="col-12 px-2 py-2 mt-4 mb-4 rounded shadow" action="<?=Url::to(['blocos/realiza-cadastro-blocos']);?>" method="post">

        <select name="from_condominio" class="custom-select mt-2">
            <option value="">Selecione o Condominio</option>
            <?
            foreach (CondominiosController::listaCondominiosSelect() as $condo) {
            ?>
                <option value="<?= $condo['id'] ?>"><?= $condo['nome'] ?></option>
            <? } ?>
        </select>

        <input class="col col-12 mt-2 form-control" type="text" name="nomeBloco" value="" placeholder="Nome do Bloco" required>
        <input class="col col-12 mt-2 form-control" type="text" name="Andares" value="" placeholder="Andares" required>
        <input class="col col-12 mt-2 form-control" type="text" name="qtUnidadesAndar" value="" placeholder="Qtd de Unidades por Andar">

        <input type="hidden" name="<?= yii::$app->request->csrfParam; ?>" value="<?= yii::$app->request->csrfToken; ?>">

        <button class="btn btn-info mt-2 col col-12 buttonEnviar" type="submit">Enviar</button>
    </form>
</div>

views/blocos/edita-blocos.php
<?

use app\components\selectedComponent;
use app\components\modalComponent;
use app\controllers\CondominiosController;
use yii\helpers\Url;
?>

<div class="row justify-content-center">

    <h1 class="text-center text-dark">Cadastro de Bloco</h1>
    <form id="form-bloco" class="col-12 px-2 py-2 mt-4 mb-4 rounded" action="<?=Url::to(['blocos/realiza-edicao-blocos']);?>" method="post">

    <select name="from_condominio" class="custom-select mt-2 fromAdministradora">
    <option value="">Selecione um Condomínio</option>
                <? 
               foreach(CondominiosController::listaCondominiosSelect() as $cond){?>
                <option value="<?=$cond['id']?>"<?=selectedComponent::isSelected($cond['id'], $edit['from_condominio'])?>><?=$cond['nome']?></option>
                <? } ?>
    </select>

        <input class="col col-12 mt-2 form-control" type="text" name="nomeBloco" value="<?= $edit['nomeBloco'] ?>" placeholder="Nome do Bloco" required>
        <input class="col col-12 mt-2 form-control" type="text" name="Andares" value="<?= $edit['Andares'] ?>" placeholder="Andares" required>
        <input class="col col-12 mt-2 form-control" type="text" name="qtUnidadesAndar" value="<?= $edit['qtUnidadesAndar'] ?>" placeholder="Qtd de Unidades por Andar">

        <input type="hidden" name="id" value="<?=$edit['id']?>">

        <input type="hidden" name="<?= yii::$app->request->csrfParam; ?>" value="<?= yii::$app->request->csrfToken; ?>">

        <div class="col col-12 mt-2 mx-0 form-group">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button class="btn btn-primary buttonEnviar" type="submit">Salvar</button>
        </div>
        <!-- <button class="btn btn-info mt-2 col col-12 buttonEnviar" type="submit">Enviar</button> -->
    </form>
</div>

views/blocos/listar-blocos.php
<?

use app\components\modalComponent;
use yii\helpers\Html;
use yii\widgets\LinkPager;
use yii\helpers\url;

$url_site = Url::base($schema = true);

?>
<h1 class="text-center">Blocos</h1>
<ul>

<table class="container-fluid table table-dark table-striped table-responsive-md mt-4" id="listaBloco">
    <tr>
        <td>Nome</td>
        <td>Condominio</td>
        <td>Andares</td>
        <td>Qtd unidades/Andar</td>
        <td>Data Cadastro</td>
        <td align="center"><a href="cadastroCondominio" class="btn btn-info">Cadastrar</a></td>
        <td colspan="2"></td>
    </tr>

    <?
    foreach ($blocos as $dadosBloco) {
    ?>
        <tr data-id="<?=$dadosBloco['id']?>">
            <td><?= $dadosBloco['nomeBloco'] ?></td>
            <td><?= $dadosBloco['nome'] ?></td>
            <td><?= $dadosBloco['Andares'] ?></td>
            <td><?= $dadosBloco['qtUnidadesAndar'] ?></td>
            <td><?=Yii::$app->formatter->format($dadosBloco['dataCadastro'],'date')?></td>
            <td align="center">
                <a href="<?=$url_site?>/index.php?r=blocos/edita-blocos&id=<?= $dadosBloco['id'] ?>" class="openModal"><i class="bi bi-pencil-square text-info"></i></a>
                <a href="<?=$url_site?>?r=blocos/deleta-blocos&id=<?=$dadosBloco['id']?>" data-id="<?= $dadosBloco['id'] ?>" class="removerCondo"><i class="bi bi-trash-fill text-info"></i></a>
            </td>
            <td></td>
            <td></td>
        </tr>
    <? } ?>
</table>

<div class="totalRegistros col-12 float-right">
    Total Registros <?=$paginacao->totalCount?>
</div>

<div class="row">
    <div class="col-12 mt-2">
            <?= LinkPager::widget(
            [
                'pagination' => $paginacao, 
                'linkContainerOptions' => [
                    'class' => 'page-item bg-dark text-info border-info'
                    ]
                , 'linkOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ],
                'disabledListItemSubTagOptions' => [
                    'class' => 'page-link bg-dark text-info border-info'
                ]
            ]
            ) ?>
    </div>
</div>

<?=modalComponent::initModal()?>